#!/bin/bash
# Helper script to launch games with Sarek agg Profile Outside of Proton

# Set The Env Variables to Run the Program under Software Rendering Mode
export LIBGL_ALWAYS_SOFTWARE="1"
export __GLX_VENDOR_LIBRARY_NAME="mesa"
export MESA_VK_DEVICE_SELECT="10005:0!"

# Launch the specified program with the environment variables
"$@"

