#!/bin/bash
# Helper script to launch games/programs with Software Rendering.

# Set The Env Variables to run the Program under OpenGL Thread Optimizations on Mesa and NVIDIA drivers
export __GL_THREADED_OPTIMIZATIONS="1"
export mesa_glthread="true"

# Process potential environment variable assignments
while [[ "$1" =~ "=" ]]; do
  export "$1"
  shift
done

# Launch the specified program with the environment variables
"$@"

